### ISSUE TITLE
[Bug]:Enhanced Celestials spamming in chat

### ISSUE THREAD

**Issue by davidl1459** [CorgiTaco/Enhanced-Celestials#247]
### Minecraft Version

1.21.1

### Enhanced Celestials Version

1.20.1-5.0.3.1

### Mod Loader

Fabric

### Mod Loader Version

1.0.3

### Bug Severity

Minor

### What happened?

<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/60199428-b961-468a-a6fd-2747a93adc5f" />

basically I did the /ec setlunarevent #enhancedcelestials:moon it will say "The ... Moon rises... " and it's random. and when it's day time it disappears but when it's night time it spams the chat "The ... Moon sets..." the example is in the attached picture

### latest.log

[latest.log](https://github.com/user-attachments/files/21427349/latest.log)

**Comment by java-jambalaya** [comment]
Getting same issue in Forge 1.20.1-5.0.3.1. Had this happen with Blood Moons seemingly at random, had to stop chat spam by running `/time add 1d`.

**Comment by MoonsMess** [comment]
This has happened to me as well

**Comment by java-jambalaya** [comment]
Bug seems to have come from version 5.0.3.0 (or later), I've been unable to reproduce this in 1.20.1-5.0.2.3-forge.

**Comment by hiimrickross** [comment]
on 5.0.2.3 fabric it still occurs, but given theres another (i'm assuming it's legit and not something else) report about adding to server then removing left the user with lowered hostile mob spawn rates, maybe some files are left over from my initial 5.0.3.1 install somewhere still causing the constant spam when changing between day/night with the time command.

**Comment by java-jambalaya** [comment]
Update: I have since been able to reproduce this on 1.20.1-5.0.2.3-forge, and reliably with these steps:
1. Create a new world
2. Run `/ec setLunarEvent enhancedcelestials:blood_moon`
3. Run `/time add 1d`
4. Run `/time set 0`
5. Run `/time set night`

And the chat should spam with `The "Blood Moon" sets... The undead begin to burn...`

My guess is that whenever a lunar event is set on a specific night and that night has already technically passed then it gets confused, since `/time set 0` sets it back to the start of day 0.

**Comment by Narcifal** [comment]
@CorgiTaco Is the fix planned?

**Comment by Lerrycapetime** [comment]
Is there any way to fix this issue right now? it's actually bugging me

**Comment by HonzaTich09** [comment]
Has this been solved? I see CorgiTaco just closing this topic, but it happens in my game still

**Comment by CorgiTaco** [comment]
@HonzaTich09 For 1.21 yes it was fixed on latest

**Comment by Joghe5** [comment]
I still have this bug happening to me, anyone has figured out how to fix it yet????
I'm on 1.20.1

**Comment by java-jambalaya** [comment]
> I still have this bug happening to me, anyone has figured out how to fix it yet???? I'm on 1.20.1

I've found it links to day count, as if it gets confused when triggering a lunar event on a night that has already passed before on that world. Since `/time set day` sets the day back to day 0, don't use `/time set __` and only use `/time add __`. If you don't know what day your world might have been up to before the bug started happening, just try `/time add 1000d` or so.

This has worked to fix it for me on Forge 1.20.1.
